-- ============================================================
--  FlipujKáru — naplnění „Ukázek úspěšných flipů" do tabulky cars
--  Vygenerováno z FLIPS v src/data/content.js (fotky v public/flips,
--  originály v data/ukazky_flipu). Každý flip = auto se status 'sold'.
--  Bezpečné pustit opakovaně: vkládá jen flipy, které v DB ještě nejsou
--  (shoda značka + model + prodejní cena mezi prodanými auty). Výjimka: BMW X6
--  už v DB existuje jako prodané auto bez příběhu → doplní se mu údaje.
-- ============================================================

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'BMW', '530d xDrive Touring M', 2018, 509000, 'denni', 'sold', 0, '/flips/bmw-530d-touring.jpg', '["/flips/bmw-530d-touring.jpg"]'::jsonb, 'PRODÁNO', 'sold', 429000, 9000, 509000, 4, 'Mnichov, Německo', 'Algoritmus zachytil dovozový inzerát v Německu — cena seděla i přes vyšší nájezd díky M-Paketu a bohaté výbavě.', '["Lakovaný levý zadní blatník po drobné nehodě (transparentně uvedeno v inzerátu)","Vyšší nájezd 157 800 km"]'::jsonb, '["Transparentní popis opravy přímo v inzerátu vč. fotky","Standardní příprava k prodeji"]'::jsonb, 'M-Paket a kompletní výbava táhly zájem navzdory vyššímu nájezdu. Kupci vadil málokdy — spíš se ptali na důvod laku, dostali upřímnou odpověď a auto si odvezli do týdne od prohlídky.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'BMW' and model = '530d xDrive Touring M' and sell_price = 509000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Audi', 'SQ5 3.0 TFSI 260 kW', 2018, 729000, 'denni', 'sold', 1, '/flips/audi-sq5.jpg', '["/flips/audi-sq5.jpg"]'::jsonb, 'PRODÁNO', 'sold', 619800, 19000, 729000, 9, 'Praha, Česko', 'Vůz z aukce, kde díky málo poptávanému provedení šla cena hluboko pod tržní úroveň — jedinečnost na trhu ale znamenala i delší prodej.', '["Poškozený lak na levém předním blatníku (stříkance)","Zanedbaný interiér","Potřeba výměny oleje"]'::jsonb, '["Kompletní přeleštění celého vozu","Ozonové čištění a hloubkové čištění interiéru","Výměna oleje","Oprava a přelakování předního blatníku"]'::jsonb, 'Skvělá nákupní cena, ale s autem bylo víc práce než obvykle. Po důkladné přípravě se přesto prodalo se ziskem přes 90 000 Kč — jen to trvalo o něco déle, protože SQ5 v této konfiguraci nemá na trhu moc srovnání.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Audi' and model = 'SQ5 3.0 TFSI 260 kW' and sell_price = 729000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon R-Line 2.0 TDI 110 kW', 2021, 567000, 'denni', 'sold', 2, '/flips/arteon-rline-110kw.jpg', '["/flips/arteon-rline-110kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 519000, 4000, 567000, 4, 'Praha, Česko', 'Vůz z aukce, který jsme sledovali kvůli konkrétní motorizaci a výbavě R-Line.', '["Segment, kde kupci automaticky srovnávají s konkurencí"]'::jsonb, '["Standardní příprava a detailing","Drobné doladění před inzercí"]'::jsonb, 'Auto se nakonec prodalo se ziskem, ale trvalo to déle — lidi v tomhle segmentu systematicky srovnávají Arteon se Superbem Combi a dávají mu přednost, ne kvůli karoserii, ale kvůli značce a servisní dostupnosti.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon R-Line 2.0 TDI 110 kW' and sell_price = 567000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon R-Line 2.0 TDI 110 kW', 2023, 699800, 'denni', 'sold', 3, '/flips/arteon-rline-blue-own.jpg', '["/flips/arteon-rline-blue-own.jpg"]'::jsonb, 'PRODÁNO', 'sold', 629300, 0, 699800, 3, 'Brno, Česko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — auto bylo v top stavu"]'::jsonb, '["Jen standardní příprava a focení, žádné opravy"]'::jsonb, 'Modrá barva byla první, co lidi na inzerátu zaujala — na trhu jsou skoro všechny R-line kusy černé nebo šedé, takže tenhle vyčníval. Navíc měl výbavu nad rámec běžného balíčku. První prohlídka skončila rezervací.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon R-Line 2.0 TDI 110 kW' and sell_price = 699800);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon R-Line 4MOTION', 2023, 749000, 'denni', 'sold', 4, '/flips/arteon-rline-4motion-aukce.jpg', '["/flips/arteon-rline-4motion-aukce.jpg"]'::jsonb, 'PRODÁNO', 'sold', 649000, 20000, 749000, 3, 'Drážďany, Německo', 'Vůz z aukce, který k nám přijel přímo z Německa.', '["Nutnost přehlášení a STK po dovozu","Drobné kosmetické nedostatky interiéru i exteriéru"]'::jsonb, '["Přehlášení a STK","Drobný detailing interiéru a exteriéru","Kompletní servis"]'::jsonb, 'První týden šel na papíry, inzerát jsme vystavili až druhý týden — ale hned se ozvali tři zájemci. Nejvážnější dojel z Ostravy, na testovačce ho dostala Alcantara a DCC podvozek. Auto odjelo 21. den s plnou nádrží jako bonus.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon R-Line 4MOTION' and sell_price = 749000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon R-Line 2.0 TDI 110 kW', 2023, 705450, 'denni', 'sold', 5, '/flips/arteon-rline-gray.jpg', '["/flips/arteon-rline-gray.jpg"]'::jsonb, 'PRODÁNO', 'sold', 631500, 0, 705450, 2, 'Zlín, Česko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — top stav a nízký nájezd"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Hnědá barva, nízký nájezd a výbava nad běžný standard R-line z něj dělaly jasnou raritu — prodalo se to nejrychleji ze všech Arteonů, které jsme ten rok měli.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon R-Line 2.0 TDI 110 kW' and sell_price = 705450);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon Shooting Brake R-Line', 2022, 599500, 'denni', 'sold', 6, '/flips/arteon-rline-shooting-brake.jpg', '["/flips/arteon-rline-shooting-brake.jpg"]'::jsonb, 'PRODÁNO', 'sold', 549800, 10000, 599500, 5, 'Lipsko, Německo', 'Algoritmus zachytil dovozový inzerát v Německu — kombík Shooting Brake s nízkým nájezdem.', '["Chybějící DCC podvozek a Head-Up display, co kupci často očekávají","Delší doba na trhu"]'::jsonb, '["Papíry a příprava (týden)","Sleva 25 000 Kč po třech týdnech bez zájmu"]'::jsonb, 'Inzerát visel skoro tři týdny bez vážnějšího zájmu — lidi se ptali hlavně na výbavu, co tenhle kus neměl. Po slevě se ozval kupec ze Zlína, kterému šlo hlavně o nízký nájezd a spolehlivý diesel. Auto si odvezl hned.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon Shooting Brake R-Line' and sell_price = 599500);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Audi', 'A6 Avant quattro S-line 210 kW', 2022, 679800, 'denni', 'sold', 7, '/flips/audi-a6-210kw.jpg', '["/flips/audi-a6-210kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 579000, 44780, 679800, 7, 'Norimberk, Německo', 'Algoritmus zachytil dovozový inzerát v Německu — výbava S-line za cenu, která seděla.', '["Chybějící matrix světla, které kupci u S-line automaticky čekají","Zvuk z přední nápravy při přejímce"]'::jsonb, '["Oprava přední nápravy před zařazením do prodeje","Standardní příprava a detailing"]'::jsonb, 'Skoro každý zájemce se hned ptal na matrix světla, a když zjistil, že tam nejsou, dost jich odpadlo. K tomu se přidala oprava nápravy. Prodej se pořádně natáhl, nakonec se ale se ziskem prodalo — jen s tenčí marží, než jsme čekali.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Audi' and model = 'A6 Avant quattro S-line 210 kW' and sell_price = 679800);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'BMW', '520d xDrive M-paket', 2025, 1599000, 'denni', 'sold', 8, '/flips/bmw-520-xdrive.jpg', '["/flips/bmw-520-xdrive.jpg"]'::jsonb, 'PRODÁNO', 'sold', 1349000, 54000, 1599000, 8, 'Mnichov, Německo', 'Algoritmus zachytil téměř nový vůz v záruce — bílý interiér, 4zónová klimatizace a Head-Up display za výbornou cenu.', '["Základní vzhled bez odlišení od běžného 520 v základu"]'::jsonb, '["Vlastní úprava vzhledu — Maxton lipa přední/zadní spoiler","Dechrom","Přestříkání kol na černo"]'::jsonb, 'Auto jsme si vzali a upravili podle vlastního vkusu. Vypadalo úplně jinak než typický 520 v základu — zájemci si toho hned všimli a byli ochotní si za ten look připlatit. Nakonec jsme dosáhli výrazně vyššího zisku, než jsme čekali.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'BMW' and model = '520d xDrive M-paket' and sell_price = 1599000);

update public.cars set buy_price = 1680690, repair_cost = 0, sell_price = 1799999, flip_weeks = 3, location = 'Miláno, Itálie', found_note = 'Algoritmus zachytil dovozový inzerát v Itálii — luxusní SUV s výbavou a zárukou hluboko pod tržní cenou.', problems = '["Italský původ, který u kupců budí přirozenou opatrnost"]'::jsonb, work = '["Důkladné prověření historie a právního stavu","Standardní příprava k prodeji"]'::jsonb, story = 'Italský původ jsme prověřili do detailu — bez problémů a se zárukou. Prodej šel rychleji, než jsme čekali.', sort = 9
where status = 'sold' and brand = 'BMW' and model like 'X6%' and story is null;

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Cupra', 'Formentor 1.5 TSI 110 kW', 2021, 499000, 'denni', 'sold', 10, '/flips/cupra-formentor-15tsi.jpg', '["/flips/cupra-formentor-15tsi.jpg"]'::jsonb, 'PRODÁNO', 'sold', 460000, 0, 499000, 1, 'Drážďany, Německo', 'Flip na objednávku pro konkrétního klienta — dostali jsme jasnou specifikaci a přes naši síť partnerů v Německu jsme mu našli hned několik aut na výběr.', '["Žádné — auto splňovalo přesnou specifikaci klienta"]'::jsonb, '["Vyřízení dovozu a přihlášení do 3 dní"]'::jsonb, 'Za dohodnutých podmínek měl klient auto doma přihlášené do tří dnů. O pár měsíců později Cupru prodal o 37 500 Kč dráž — vyzkoušel si na jednom autě, jaké to je flipovat, zatímco ho běžně používal.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Cupra' and model = 'Formentor 1.5 TSI 110 kW' and sell_price = 499000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Cupra', 'Formentor VZ2 2.0 TSI 228 kW', 2022, 649500, 'denni', 'sold', 11, '/flips/cupra-formentor-vz2.jpg', '["/flips/cupra-formentor-vz2.jpg"]'::jsonb, 'PRODÁNO', 'sold', 590000, 0, 649500, 1, 'Stuttgart, Německo', 'Algoritmus zachytil dovozový inzerát v Německu, ale sourcování bylo náročné — top verze VZ2 se na trhu neobjevuje často.', '["Obtížná dostupnost — vysoce žádaná verze VZ2"]'::jsonb, '["Dovoz a příprava bez klasické inzerce"]'::jsonb, 'Obtížné sourcování se vyplatilo — auto šlo rovnou ke klientovi bez inzerce a bez vyjednávání o ceně.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Cupra' and model = 'Formentor VZ2 2.0 TSI 228 kW' and sell_price = 649500);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Golf GTI Clubsport', 2023, 789300, 'denni', 'sold', 12, '/flips/golf-clubsport-gti.jpg', '["/flips/golf-clubsport-gti.jpg"]'::jsonb, 'PRODÁNO', 'sold', 729500, 0, 789300, 3, 'Norimberk, Německo', 'Klient hledal konkrétně GTI s nízkým nájezdem a pěkně vybaveným interiérem — ne obyčejnou verzi z flotily. Hledání přes naši síť v Německu trvalo přes tři týdny.', '["Většina nabídek na trhu byla buď přejetá, nebo v základní výbavě"]'::jsonb, '["Cílené hledání přesně podle klientovy specifikace"]'::jsonb, 'Nakonec se sehnal kus přesně podle představ. Klient si ho po předání pochvaloval jako „přesně to, co jsem si vysnil“ — žádná inzerce, žádné smlouvání, auto šlo rovnou k novému majiteli.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Golf GTI Clubsport' and sell_price = 789300);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Mercedes-Benz', 'CLA 180 Kupé', 2020, 619000, 'denni', 'sold', 13, '/flips/mercedes-cla-180.jpg', '["/flips/mercedes-cla-180.jpg"]'::jsonb, 'PRODÁNO', 'sold', 519900, 23500, 619000, 4, 'Praha, Česko', 'Vůz z aukce, který jsme vybrali díky ceně hluboko pod srovnatelnými kusy na trhu.', '["Opotřebený zadní nárazník","Potřeba výměny oleje a hloubkového čištění"]'::jsonb, '["Výměna oleje","Hloubkové čištění interiéru","Oprava zadního nárazníku","Leštění laku"]'::jsonb, 'Po servisu a kosmetických opravách se auto prodalo rychle a se solidním ziskem přes 75 000 Kč.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Mercedes-Benz' and model = 'CLA 180 Kupé' and sell_price = 619000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Mercedes-Benz', 'CLS 400d 4MATIC AMG Line', 2019, 1459000, 'denni', 'sold', 14, '/flips/mercedes-cls-400d.jpg', '["/flips/mercedes-cls-400d.jpg"]'::jsonb, 'PRODÁNO', 'sold', 1270000, 0, 1459000, 11, 'Mnichov, Německo', 'Algoritmus zachytil skvělý dovoz z Německa — auto v super stavu s možností prodloužit záruku, byť model se už nevyrábí, takže jsme trochu zariskovali.', '["Slabší výbava oproti konkurenci v této cenové kategorii","Delší doba prodeje kvůli ukončené výrobě modelu"]'::jsonb, '["Prověření a prodloužení záruky","Standardní příprava k prodeji"]'::jsonb, 'Věděli jsme, že podle rozdílu mezi nákupní a lokální prodejní cenou bude marže vysoká, i když prodej potrvá déle. Vyplatilo se — čistý zisk skoro 190 000 Kč.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Mercedes-Benz' and model = 'CLS 400d 4MATIC AMG Line' and sell_price = 1459000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Passat 2.0 TDI Highline', 2023, 554500, 'denni', 'sold', 15, '/flips/passat-20tdi-highline.jpg', '["/flips/passat-20tdi-highline.jpg"]'::jsonb, 'PRODÁNO', 'sold', 535200, 4000, 554500, 9, 'Vídeň, Rakousko', 'Algoritmus zachytil dovozový inzerát v Rakousku s nízkým nájezdem.', '["Špatně čtený segment trhu — kupci u Passatu čekají buď starší levnější kus, nebo rovnou sáhnou po Superbu","Slabá vizuální modernizace modelu"]'::jsonb, '["Standardní příprava k prodeji"]'::jsonb, 'Auto samo o sobě bylo v pořádku, ale trh ho špatně přijal. Nakonec se prodalo se ziskem, jen mnohem tenčím, než jsme čekali — cenná lekce, na jaký segment se příště zaměřit.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Passat 2.0 TDI Highline' and sell_price = 554500);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Kodiaq 2.0 TDI Sportline 147 kW', 2021, 705000, 'denni', 'sold', 16, '/flips/skoda-kodiaq-sportline.jpg', '["/flips/skoda-kodiaq-sportline.jpg"]'::jsonb, 'PRODÁNO', 'sold', 599000, 0, 705000, 6, 'Praha, Česko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — auto bez chyby s kompletní historií"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Auto bez chyby s kompletní historií vyneslo vysoký zisk přes 100 000 Kč. Co nás překvapilo, byl o něco delší prodej, než jsme u tak čistého kusu čekali.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Kodiaq 2.0 TDI Sportline 147 kW' and sell_price = 705000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Octavia RS 2.0 TDI 4x4', 2021, 649000, 'denni', 'sold', 17, '/flips/skoda-octavia-rs.jpg', '["/flips/skoda-octavia-rs.jpg"]'::jsonb, 'PRODÁNO', 'sold', 564000, 0, 649000, 2, 'Brno, Česko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — top stav bez práce navíc"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Další z řady bezproblémových rychlých flipů. Auto v top stavu bez práce navíc, rychlý prodej, rychlý zisk přes 85 000 Kč.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Octavia RS 2.0 TDI 4x4' and sell_price = 649000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Scala 1.5 TSI Automat', 2023, 429300, 'denni', 'sold', 18, '/flips/skoda-scala-black.jpg', '["/flips/skoda-scala-black.jpg"]'::jsonb, 'PRODÁNO', 'sold', 397800, 0, 429300, 2, 'Košice, Slovensko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — jen nižší cenový strop segmentu"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Nadstandardní výbava (panorama a další) a skvělý stav udělaly z tohoto kusu dobrou koupi. Prodáno mírně pod tržní cenou, takže zisk byl menší, ale jistý a rychlý.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Scala 1.5 TSI Automat' and sell_price = 429300);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Scala Monte Carlo 1.5 TSI 110 kW', 2022, 467500, 'denni', 'sold', 19, '/flips/skoda-scala-blue-montecarlo.jpg', '["/flips/skoda-scala-blue-montecarlo.jpg"]'::jsonb, 'PRODÁNO', 'sold', 429200, 0, 467500, 1, 'Žilina, Slovensko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — top výbava a stav"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Nádherná Scala v top výbavě prodaná bleskově do týdne — jeden z nejrychlejších flipů v naší evidenci.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Scala Monte Carlo 1.5 TSI 110 kW' and sell_price = 467500);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Sportline 110 kW', 2023, 669600, 'denni', 'sold', 20, '/flips/skoda-superb-sportline-110kw.jpg', '["/flips/skoda-superb-sportline-110kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 587700, 5000, 669600, 1, 'Berlín, Německo', 'Algoritmus zachytil dovozový inzerát v Německu.', '["Lak na blatníku a dveřích po drobné opravě"]'::jsonb, '["Transparentní popis opravy přímo v inzerátu vč. fotek"]'::jsonb, 'Lak jsme rovnou napsali do inzerátu i s fotkami, žádné skrývání. Zájemci to ocenili jako důkaz upřímnosti. Interiér byl krásně zachovalý, což na fotkách i na prohlídce zabodovalo — prodáno během devíti dní bez větší slevy.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Sportline 110 kW' and sell_price = 669600);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Selection 110 kW', 2025, 749540, 'denni', 'sold', 21, '/flips/skoda-superb-selection.jpg', '["/flips/skoda-superb-selection.jpg"]'::jsonb, 'PRODÁNO', 'sold', 669700, 34560, 749540, 5, 'Praha, Česko', 'Vůz z aukce, kde jsme s odřenkami počítali dopředu.', '["Spousta drobných škrábanců — typické pro aukční vůz","Základní výbava omezující cenový strop"]'::jsonb, '["Korekce laku","Přelakování zadního nárazníku"]'::jsonb, 'Po korekci laku a přelakování zadního nárazníku vypadalo auto naprosto čerstvě. Základní výbava omezovala cenový strop, ale díky levnému nákupu a poctivé opravě zůstal slušný zisk.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Selection 110 kW' and sell_price = 749540);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Sportline 4x4 147 kW', 2023, 683400, 'denni', 'sold', 22, '/flips/skoda-superb-sportline-4x4-grey.jpg', '["/flips/skoda-superb-sportline-4x4-grey.jpg"]'::jsonb, 'PRODÁNO', 'sold', 605400, 0, 683400, 1, 'Verona, Itálie', 'Auto od německého partnera s italským původem — díky důkladnému prověření historie jsme sehnali super auto za super cenu.', '["Italský původ, který u kupců budí přirozenou opatrnost"]'::jsonb, '["Důkladné prověření historie a právního stavu"]'::jsonb, 'Ne každé auto s italským původem je problém, důležité je důkladné prověření a dobrý kontakt na místě. Původní lak, žádné skryté škody. Klient byl informovaný o celém procesu od A do Z, takže ho na konci nic nepřekvapilo.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Sportline 4x4 147 kW' and sell_price = 683400);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Style 110 kW', 2022, 610000, 'denni', 'sold', 23, '/flips/skoda-superb-style-110kw.jpg', '["/flips/skoda-superb-style-110kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 530000, 0, 610000, 2, 'Plzeň, Česko', 'Vůz z vlastní sítě kontaktů, bez zveřejněné inzerce.', '["Žádné — kompletní historie bez nákladů navíc"]'::jsonb, '["Jen standardní příprava a focení"]'::jsonb, 'Rychlý prodej, pěkné auto s kompletní historií, bez nákladů navíc — jednoduchý flip, jak má být.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Style 110 kW' and sell_price = 610000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Sportline 147 kW', 2022, 649000, 'denni', 'sold', 24, '/flips/skoda-superb-sportline-147kw.jpg', '["/flips/skoda-superb-sportline-147kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 569000, 19000, 649000, 3, 'Mnichov, Německo', 'Algoritmus zachytil dovozový inzerát v Německu.', '["Kontrolka motoru před předáním — vadný dávkovací vstřikovač AdBlue","Německý prodejce odmítl reklamaci uznat"]'::jsonb, '["Diagnostika a výměna vstřikovače AdBlue (10 000 Kč)","Doleštění drobných oděrek laku"]'::jsonb, 'Klient byl domluvený rychle, ale těsně před předáním se rozsvítila kontrolka motoru. Německý prodejce reklamaci odmítl, takže jsme vadný vstřikovač vyměnili sami. Zdrželo nás to o pár dní, ale kupec zůstal ve hře a auto koupil krátce po opravě.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Sportline 147 kW' and sell_price = 649000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Škoda', 'Superb Sportline 4x4 147 kW', 2022, 689950, 'denni', 'sold', 25, '/flips/skoda-superb-sportline-4x4-147kw.jpg', '["/flips/skoda-superb-sportline-4x4-147kw.jpg"]'::jsonb, 'PRODÁNO', 'sold', 597600, 9000, 689950, 2, 'Drážďany, Německo', 'Algoritmus zachytil dovozový inzerát v Německu.', '["Dost škrábanců na exteriéru","Odlomená mlhovka"]'::jsonb, '["Vyleštění celého exteriéru","Dokoupení a výměna mlhovky"]'::jsonb, 'Po vyleštění vypadal vůz jako nový. Top stav, top výbava a oblíbené tažné zařízení — takové auto se prodává samo, radost prodávat.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Škoda' and model = 'Superb Sportline 4x4 147 kW' and sell_price = 689950);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Tiguan 1.5 TSI 110 kW', 2022, 539000, 'denni', 'sold', 26, '/flips/vw-tiguan-15tsi.jpg', '["/flips/vw-tiguan-15tsi.jpg"]'::jsonb, 'PRODÁNO', 'sold', 475000, 5000, 539000, 6, 'Praha, Česko', 'Vůz z aukce, který jsme hlídali kvůli konkrétní motorizaci.', '["Bez Virtual Cockpitu — kupci to vnímají jako chybějící výbavu","Pouze 4x2 pohon, zatímco u SUV segmentu lidé automaticky čekají 4x4"]'::jsonb, '["Standardní příprava k prodeji"]'::jsonb, 'Prodávalo se déle, protože chybějící Virtual Cockpit a jen přední pohon segmentu SUV kupcům nesedí, i když to reálně nepotřebují. Dobrá nákupní cena to nakonec vykompenzovala.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Tiguan 1.5 TSI 110 kW' and sell_price = 539000);

insert into public.cars (brand, model, year, price, category, status, sort, image_url, images, badge_text, badge_tone, buy_price, repair_cost, sell_price, flip_weeks, location, found_note, problems, work, story)
select 'Volkswagen', 'Arteon Shooting Brake Elegance', 2023, 679000, 'denni', 'sold', 27, '/flips/vw-arteon-elegance.jpg', '["/flips/vw-arteon-elegance.jpg"]'::jsonb, 'PRODÁNO', 'sold', 590000, 5000, 679000, 2, 'Norimberk, Německo', 'Algoritmus zachytil dovozový inzerát v Německu — nízký nájezd u tříletého kusu byl hlavním lákadlem.', '["Žádné zásadní — jen běžná příprava"]'::jsonb, '["Standardní příprava a focení interiéru"]'::jsonb, 'Inzerát vyvolal zájem hned první den — fotky interiéru s pěknou výbavou prodávaly auto samy. První zájemce přijel na prohlídku, po testovačce se ptal jen na servisní historii a rovnou dal zálohu. Nízký nájezd byl hlavní argument, o kterém se ani nemuselo smlouvat.'
where not exists (select 1 from public.cars where status = 'sold' and brand = 'Volkswagen' and model = 'Arteon Shooting Brake Elegance' and sell_price = 679000);

